# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-27 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0002_auto_20170122_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='level',
            field=models.IntegerField(verbose_name=b'\xe6\x97\xa5\xe5\xbf\x97\xe7\xad\x89\xe7\xba\xa7'),
        ),
        migrations.AlterField(
            model_name='log',
            name='operation',
            field=models.CharField(max_length=128, verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c'),
        ),
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.DateTimeField(verbose_name=b'\xe6\x97\xa5\xe5\xbf\x97\xe6\x97\xb6\xe9\x97\xb4'),
        ),
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(max_length=16, verbose_name=b'\xe6\x97\xa5\xe5\xbf\x97\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.CharField(max_length=32, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
    ]
