# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-27 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0003_auto_20170122_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpudata',
            name='cpuload',
            field=models.IntegerField(verbose_name=b'cpu\xe4\xbd\xbf\xe7\x94\xa8\xe7\x8e\x87'),
        ),
        migrations.AlterField(
            model_name='cpudata',
            name='serviceid',
            field=models.IntegerField(verbose_name=b'\xe4\xb8\xbb\xe6\x9c\xbaid'),
        ),
        migrations.AlterField(
            model_name='cpudata',
            name='time',
            field=models.DateTimeField(verbose_name=b'\xe7\x9b\x91\xe6\x8e\xa7\xe6\x97\xb6\xe9\x97\xb4'),
        ),
        migrations.AlterField(
            model_name='serveruser',
            name='serverUserName',
            field=models.CharField(max_length=32, verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d'),
        ),
        migrations.AlterField(
            model_name='serveruser',
            name='serverUserPasswd',
            field=models.CharField(max_length=32, verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8\xe5\xaf\x86\xe7\xa0\x81'),
        ),
        migrations.AlterField(
            model_name='serveruser',
            name='serviceid',
            field=models.IntegerField(verbose_name=b'\xe4\xb8\xbb\xe6\x9c\xbaid'),
        ),
        migrations.AlterField(
            model_name='service',
            name='disk',
            field=models.CharField(max_length=32, verbose_name=b'\xe7\xa3\x81\xe7\x9b\x98'),
        ),
        migrations.AlterField(
            model_name='service',
            name='host',
            field=models.CharField(max_length=32, verbose_name=b'\xe4\xb8\xbb\xe6\x9c\xba\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
        migrations.AlterField(
            model_name='service',
            name='ip',
            field=models.CharField(max_length=32, verbose_name=b'\xe4\xb8\xbb\xe6\x9c\xbaip'),
        ),
        migrations.AlterField(
            model_name='service',
            name='mem',
            field=models.CharField(max_length=32, verbose_name=b'\xe5\x86\x85\xe5\xad\x98'),
        ),
        migrations.AlterField(
            model_name='service',
            name='model',
            field=models.CharField(max_length=32, verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8\xe5\x9e\x8b\xe5\x8f\xb7'),
        ),
        migrations.AlterField(
            model_name='service',
            name='system',
            field=models.CharField(max_length=32, verbose_name=b'\xe7\xb3\xbb\xe7\xbb\x9f'),
        ),
    ]
