# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-27 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20170227_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='groups',
            field=models.ManyToManyField(to='User.Group'),
        ),
        migrations.AddField(
            model_name='method',
            name='users',
            field=models.ManyToManyField(to='User.User'),
        ),
    ]
